<div style="float:right; padding-top: 15px; padding-right: 15px">
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="250">
        </a>
    </div>
</div>

# Numpy

In [1]:
import numpy as np

The basic data structures in Numpy are arrays, which can be used to represent tabular data. You can think of arrays as lists of lists.
The size of an array is the total number of elements in every list. The shape of an array is the size of the array along each dimension

In [2]:
np.zeros((2))

array([0., 0.])

In [3]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a = np.zeros((5,4,2))

a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [7]:
print(len(a))
print(a.size)
print(a.shape)

5
40
(5, 4, 2)


In [6]:
np.zeros((3,4,2,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [7]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
a = np.random.random((10,4))

a

array([[0.95409731, 0.28203803, 0.27246235, 0.71628291],
       [0.84491119, 0.9337159 , 0.86498246, 0.293134  ],
       [0.45598296, 0.20988323, 0.93896291, 0.85915524],
       [0.03895902, 0.74270202, 0.20615158, 0.4213777 ],
       [0.66335644, 0.60382622, 0.94434903, 0.02672706],
       [0.47598075, 0.07032334, 0.60204573, 0.1912679 ],
       [0.34425334, 0.56205115, 0.80006844, 0.33741217],
       [0.74194275, 0.91407278, 0.84434249, 0.36226533],
       [0.32858608, 0.31943143, 0.86880819, 0.7750238 ],
       [0.56989738, 0.4878189 , 0.04814806, 0.64344161]])

In [10]:
my_array_random = [np.random.choice(x) for x in a]

np.random.choice(my_array_random)

0.07032334465770074

In [20]:
a.size

40

In [21]:
np.random.choice(a[0])

0.27246235287823317

In [22]:
np.reshape(a, a.size)

array([0.95409731, 0.28203803, 0.27246235, 0.71628291, 0.84491119,
       0.9337159 , 0.86498246, 0.293134  , 0.45598296, 0.20988323,
       0.93896291, 0.85915524, 0.03895902, 0.74270202, 0.20615158,
       0.4213777 , 0.66335644, 0.60382622, 0.94434903, 0.02672706,
       0.47598075, 0.07032334, 0.60204573, 0.1912679 , 0.34425334,
       0.56205115, 0.80006844, 0.33741217, 0.74194275, 0.91407278,
       0.84434249, 0.36226533, 0.32858608, 0.31943143, 0.86880819,
       0.7750238 , 0.56989738, 0.4878189 , 0.04814806, 0.64344161])

In [25]:
np.reshape(a, (a.size, 1, 1)).shape

(40, 1, 1)

In [26]:
print(a.shape)
print(a.size)

(10, 4)
40


In [27]:
# first row
a[0]

array([0.95409731, 0.28203803, 0.27246235, 0.71628291])

In [28]:
# first column
a[:,0]

array([0.95409731, 0.84491119, 0.45598296, 0.03895902, 0.66335644,
       0.47598075, 0.34425334, 0.74194275, 0.32858608, 0.56989738])

In [29]:
a[4,2]

0.9443490253799511

In [30]:
a[4][2]

0.9443490253799511

In [31]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
d.shape

(3, 3)

In [33]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9,10]]
unbalanced = np.array(lst_lst)
unbalanced

/home/victor/miniconda3/envs/ironhack_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


array([list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9, 10])],
      dtype=object)

In [34]:
unbalanced.shape

(3,)

In [35]:
np.sum(d)

45

In [36]:
np.sum(d[:,0])

12

In [37]:
np.sum(d[1,:])

15

In [25]:
np.sum(d[1])

15

In [26]:
np.sum(d, axis=0)

array([12, 15, 18])

In [27]:
np.sum(d, axis=1)

array([ 6, 15, 24])

In [28]:
np.mean(d)

5.0

In [29]:
np.mean(d, axis=0)

array([4., 5., 6.])

In [30]:
np.mean(d, axis=1)

array([2., 5., 8.])

## Operator overload

In [31]:
x = np.array([[1,2], [1,0]])
x

array([[1, 2],
       [1, 0]])

In [32]:
y = np.array([[1,2], [1,1]])
y

array([[1, 2],
       [1, 1]])

In [33]:
x + y

array([[2, 4],
       [2, 1]])

In [34]:
np.add(x,y)

array([[2, 4],
       [2, 1]])

In [35]:
np.concatenate([x, y])

array([[1, 2],
       [1, 0],
       [1, 2],
       [1, 1]])

In [36]:
?np.concatenate

Docstring:
concatenate((a1, a2, ...), axis=0, out=None)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.

Returns
-------
res : ndarray
    The concatenated array.

See Also
--------
ma.concatenate : Concatenate function that preserves input masks.
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.
split : Split array into a list of multiple sub-arrays of equal size.
hsplit : Split array into multiple sub-arrays horizontally 

In [37]:
x - y

array([[ 0,  0],
       [ 0, -1]])

In [38]:
np.subtract(x,y)

array([[ 0,  0],
       [ 0, -1]])

In [39]:
x * y

array([[1, 4],
       [1, 0]])

In [40]:
np.multiply(x,y)

array([[1, 4],
       [1, 0]])

In [41]:
x / y

array([[1., 1.],
       [1., 0.]])

In [42]:
np.divide(x,y)

array([[1., 1.],
       [1., 0.]])

In [43]:
np.matmul(x,y)

array([[3, 4],
       [1, 2]])

In [44]:
x

array([[1, 2],
       [1, 0]])

In [45]:
y

array([[1, 2],
       [1, 1]])

<div style="padding-top: 25px; float: right">
    <div>    
        <i>&nbsp;&nbsp;© Copyright by</i>
    </div>
    <div>
        <a href="https://whiteboxml.com">
            <img src="https://whiteboxml.com/static/img/logo/black_bg_white.svg" width="125">
        </a>
    </div>
</div>